server:
  port: 8080
  address: 0.0.0.0


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resumeranker
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: welcome2bunny@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.springframework.security: DEBUG

application:
  security:
    jwt:
      secret-key: YW55IHJhbmRvbSBzdHJpbmcgd2lsbCB3b3JrIGhlcmU=
      expiration: 86400000
